### PR TITLE
Format code with rustfmt and fix clippy suggestions

### PR DESCRIPTION
**Pull request by retrry**
This PR includes: https://github.com/meh/rust-ffmpeg/pull/106

I know so much code churn sucks, but I see that most of Rust projects are using rustfmt, so I think it would be good, that rust-ffmpeg used same style too (rust-ffmpeg-sys is already formatted with rustfmt). @meh what do you think about it? I think it would be better to do this change sooner than latter.

Btw, can I catch you somewhere on IRC? I would like to rewrite Input context creation to Builder pattern and I would like to coordinate it with you.

### CODE REVIEW

**Comment by retrry** [comment]
I've added commits with clippy lint fixes. You can review those on commit by commit basis. My main concern is this commit: https://github.com/meh/rust-ffmpeg/pull/107/commits/a8d642d2433a175097d2e83969449e53270a3020 as it chages rust-ffmpeg API.

**Comment by meh** [comment]
Yeah, that lint should be ignored, you want the `Range` by value.

**Comment by retrry** [comment]
Reverted that commit.

**Comment by retrry** [comment]
Hey, do you think we could land this or should I close this PR? :)

**Comment by meh** [comment]
Sorry, forgot about this entirely! :cry: 

You can catch me on the Mozilla IRC most of the time as `meh`, merging this now.

**Pull request merged**
