### PR TITLE
Format find best stream

### PR DESCRIPTION
**Pull request by lummax**
As soon as https://github.com/meh/rust-ffmpeg-sys/pull/4 is merged and published this can be merged.

### CODE REVIEW

**Comment by meh** [comment]
I'm a little unsure about the API for this one, give me some time to think about it.

**Comment by lummax** [comment]
What I don't like is the fact that there are different ways to get to a `Stream` object. All of them point to the same `AVStream` in the end, thus violating the Rust guarantees.

**Comment by meh** [comment]
I'm pretty sure the lifetime of the `format::Context` ensures the streams won't be able to change, I don't remember if there are mutable methods on `Stream`, if there are it should be split between `Stream` and `StreamMut`, and then have `*_mut` variants to access the mutable streams.

**Comment by lummax** [comment]
```rust 
extern crate ffmpeg;

use std::env;
use std::path::Path;

fn main() {
    ffmpeg::init().unwrap();
	if let Some(file) = env::args().nth(1) {
		let path = Path::new(&file);
		match ffmpeg::format::open_input(&path) {
			Err(error) => println!("Error: {}", error),
			Ok(context) => { 
                let mut stream_a = context.streams().nth(1).unwrap();
                let stream_b = context.streams().nth(1).unwrap();

                println!("{:?}", stream_b.frame_rate());
                stream_a.set_frame_rate(ffmpeg::Rational::new(42, 42));
                println!("{:?}", stream_b.frame_rate());
			},
		}
	} else { println!("Usage: metadata path/to/file") }
}
```

This gives:

    rust-ffmpeg ➤ ./target/debug/examples/test ~/Downloads/sintel_trailer-1080p.mp4
    Rational(0/0)
    Rational(42/42)

**Comment by meh** [comment]
Indeed, it should be split to prevent that, I'll open an issue to remember about it.

**Comment by lummax** [comment]
Any thoughts on this?

Would you like to have the `Option`s removed so that the user is required to input `-1` if there are no related/wanted stream?

**Comment by meh** [comment]
I'm still thinking about a better API.

Having to use indices when we have a `Stream` type sounds kinda bleh.

**Comment by meh** [comment]
Ok I think I found an API I like.

```rust
format.streams().best(type::Audio)
format.streams().wanted(stream).best(type::Audio)
format.streams().related(stream).best(type::Audio)
format.streams().wanted(stream).related(stream2).best(type::Audio)
```

Where `wanted` and `related` take a `&Stream`, thoughts?

**Comment by lummax** [comment]
`format.streams()` returns a `StreamIter` which has a pointer to the `AVCodecContext` so thats fine. And I like the first variant.

But I wonder what `format.streams().wanted(..)`  returns? In this (kind of fluent) interface we would need some intermediate object for the wanted/best selection?

And what about an exhausted iterator? Of couse this would work as the internal API just traverses the streams again, but the user might expect something differently semantically (The same if he filtered the streams somehow. `best()` would still look at all streams).

```rust
let streams = format.streams();
let count = streams.count();
let best = streams.best(..);        // <- ??

let streams2 = format.streams().filter(|s| s.index()  < 5);
let best2 = streams2.best(..);    // <- ??
```

**Comment by meh** [comment]
`streams2` wouldn't be a `StreamIter` anymore, so that's fine.

Also yes, there would be an intermediary builder for it. Let me implement it :panda_face:

**Comment by meh** [comment]
Implemented my version on master.

**Pull request closed without merging**
