### PR TITLE
Graph dumping

### PR DESCRIPTION
**Pull request by lummax**
This PR depends on https://github.com/meh/rust-ffmpeg-sys/pull/8.

### CODE REVIEW

**Comment by meh** [comment]
How does the dump look?

Maybe it would be better to implement `Display` instead.

**Comment by lummax** [comment]
It's ugly and technical. I think `Display` should be an readable representation and not a technical to debug the filtergraph.

**Comment by meh** [comment]
Maybe `Debug` then?

**Comment by meh** [comment]
I added a `dump` function for the format dumping because it actually just prints to stdout, I'd rather implement `Display` and `Debug` when possible.

**Comment by lummax** [comment]
See https://gist.github.com/lummax/669127182f9c145a2445.

I don't like the debug aswell. That's not what I would expect when using `{:?}`. But I guess it would be fine.

**Comment by meh** [comment]
Agree, I'll merge as is.

**Comment by meh** [comment]
Merged.

**Comment by lummax** [comment]
\ö/

**Pull request closed without merging**
