### PR TITLE
Audio transcoding

### PR DESCRIPTION
**Pull request by lummax**
This implements the necessary stuff to enable the ffmpeg decode-filter-encode pipeline for simple examples with audio files.

It needs the current https://github.com/meh/rust-ffmpeg-sys master branch to be published.

### CODE REVIEW

**Comment by meh** [comment]
I think I'd rather have `input*` and `output*` than `open_input*` and `open_output*`.

**Comment by lummax** [comment]
Returning the `Context` struct or `Input`/`Output`variants?

**Comment by meh** [comment]
Yeah, good question, I think we should also split `Context` into `Input` and `Output` context, I'll do that part, I'll merge this in the meantime.

**Comment by meh** [comment]
This will take a little longer, I'm rewriting the `avfilter` wrapper, and redesigning `format::Context` handling.

**Comment by lummax** [comment]
Could you elaborate on the `avfilter` rewrite? I actually have some more stuff after this first audio PR is merged.

**Comment by meh** [comment]
Well, your implementation was unsound and the API wasn't that good, I'm wrapping the whole avfilter now.

**Comment by lummax** [comment]
That might not be necessary. From what I saw you can achieve most of the filtering stuff by passing a [filterspec](http://ffmpeg.org/ffmpeg-filters.html#Filtergraph-description).

**Comment by meh** [comment]
Ok, I did a bunch of changes and made the filter stuff ergonomic and sound.

I did not include the transcode example yet because it seems to not be transcoding, as in, it takes a file with its codec, and "transcodes" it to the same codec.

Here's the updated version working with the current API changes:

```rust
extern crate ffmpeg;

use std::env;

use ffmpeg::{format, codec, frame, media, filter};
use ffmpeg::option::Settable;

fn filter(spec: &str, decoder: &codec::decoder::Audio, encoder: &codec::encoder::Audio) -> Result<filter::Graph, ffmpeg::Error> {
	let mut filter = filter::Graph::new();

	let base = ffmpeg::Rational(1, 1000000);
	let args = format!("time_base={}:sample_rate={}:sample_fmt={}:channel_layout=0x{:x}",
		base, decoder.rate(), decoder.format().name(), decoder.channel_layout().bits());

	try!(filter.add(&filter::find("abuffer").unwrap(), "in", &args));
	try!(filter.add(&filter::find("abuffersink").unwrap(), "out", ""));

	{
		let mut sink = filter.get("out").unwrap();

		sink.set_sample_format(encoder.format()).unwrap();
		sink.set_channel_layout(encoder.channel_layout()).unwrap();
		sink.set_sample_rate(encoder.rate()).unwrap();
	}

	try!(try!(try!(filter.output("in", 0)).input("out", 0)).parse(spec));
	try!(filter.validate());

	Ok(filter)
}

struct Transcoder {
	stream:  usize,
	filter:  filter::Graph,
	decoder: codec::decoder::Audio,
	encoder: codec::encoder::audio::Encoder,
}

fn transcoder(ictx: &mut format::context::Input, octx: &mut format::context::Output) -> Result<Transcoder, ffmpeg::Error> {
	let input   = ictx.streams().best(media::Type::Audio).expect("could not find best audio stream");
	let decoder = try!(input.codec().decoder().audio());
	let codec   = try!(ffmpeg::encoder::find(decoder.id()).expect("failed to find encoder").audio());

	let mut output = octx.add_stream(&codec);
	output.set_time_base(input.time_base());

	let mut encoder = try!(output.codec().encoder().audio());

	encoder.set_rate(decoder.rate() as i32);
	encoder.set_channel_layout(decoder.channel_layout());
	encoder.set_channels(decoder.channel_layout().channels());
	encoder.set_format(codec.formats().expect("unknown supported formats").next().unwrap());

	output.set_time_base((1, decoder.rate() as i32));

	let filter  = try!(filter("anull", &decoder, &encoder));
	let encoder = try!(encoder.open_as(&codec));

	Ok(Transcoder {
		stream:  input.index(),
		filter:  filter,
		decoder: decoder,
		encoder: encoder,
	})
}

fn main() {
	ffmpeg::init().unwrap();

	let mut ictx       = format::input(&env::args().nth(1).expect("missing input")).unwrap();
	let mut octx       = format::output(&env::args().nth(2).expect("missing output")).unwrap();
	let mut transcoder = transcoder(&mut ictx, &mut octx).unwrap();

	octx.write_header().unwrap();

	let time_base = (1, 1000000);
	let mut frame = frame::Audio::empty();

	for (stream, mut packet) in ictx.packets() {
		if stream.index() == transcoder.stream {
			let (os_index, os_time_base) = {
				let os = octx.stream(stream.index()).unwrap();
				(os.index(), os.time_base())
			};

			packet.rescale_ts(stream.time_base(), time_base);

			if transcoder.decoder.decode(&packet, &mut frame).unwrap() {
				// we ignore the pts here. There are several issues why:
				// - Some internet sources state that it is deprecated (or will be soon).
				// - It also works without it (for mp3).
				transcoder.filter.get("in").unwrap().source().add(&frame).unwrap();

				while let Ok(..) = transcoder.filter.get("out").unwrap().sink().frame(&mut frame) {
					let mut encoded = ffmpeg::Packet::empty();

					transcoder.encoder.encode(&frame, &mut encoded).unwrap();

					encoded.set_stream(os_index);
					encoded.rescale_ts(time_base, os_time_base);
					encoded.write_interleaved(&mut octx).unwrap();
				}
			}
		}
	}

	octx.write_trailer().unwrap();
}
```

**Pull request closed without merging**
