### PR TITLE
Updates for FFmpeg 4

### PR DESCRIPTION
**Pull request by barzamin**

### CODE REVIEW

**Comment by expenses** [comment]
@barzamin Thank you! Seeing as this repo is not being updated very often, and the crates.io crate is wayy out of date, I think we should think about switching to a different repo

**Comment by barzamin** [comment]
Yeah, I'm strongly considering forking this over somewhere else and applying all the patches that make it Actually Build on modern systems

**Comment by meh** [comment]
Does anyone want to be added as contributor and to crates.io for the time being?

**Comment by expenses** [comment]
@meh I'm a little busy, but I would be happy to help out as long as someone takes the lead of maintaining the crate.

**Comment by barzamin** [comment]
@meh i would be open to acting as an interim maintainer of the crate

**Comment by barzamin** [comment]
@meh Thought about this a bit more and I definitely have the time to do the (relatively small!) amount of work needed to bring this all up to date and maintain the crate; if you could add me as a co-maintainer, that would be awesome!

**Comment by meh** [comment]
@barzamin go for it, please use squash/rebase instead of merge if possible, I don't like merge commits unless they make sense (i.e. feature branch or whatever).

Thanks.

**Comment by ririsoft** [comment]
Thank you very much gentlemen for your work on ffmpeg bindings for rust. It is very much appreciated.

Do you have a status on how the project is going on please ? @meh are you still maintaining it ? I see @barzamin is working on it and tries to merge into your project while @zmwangx has forked the project and is working on his own renaming the project "ffmpeg-next".

I would like some visibility to understand what is the best option to collaborate on a good ffmpeg bindings for rust.

**Comment by zmwangx** [comment]
My fork hasn’t been updated to support FFmpeg 4.1 yet. (I’ll get to that soon.)

**Comment by barzamin** [comment]
@ririsoft the current issue is that `ffmpeg-sys` has been updated for ffmpeg 4 but @meh has not pushed it to crates.io yet. @meh is the only person with crates access, afaict, so any further progress on this crate is blocked on that.

**Comment by zmwangx** [comment]
ffmpeg-sys is a pretty straightforward bindgen crate and it’s not really FFmpeg 4.x aware. Not sure why you think -sys is the issue.

**Comment by barzamin** [comment]
@zmwangx because there are two patches to `-sys` that have not been published yet, which fix compilation on systems where libavresample is not present due to deprecation:
* https://github.com/meh/rust-ffmpeg-sys/commit/2937563482b8d3be302ee39c0fbb024e5408b085
* https://github.com/meh/rust-ffmpeg-sys/commit/4d2e08812818363873e2bfefcffc24e5da9a3d42

**Comment by zmwangx** [comment]
Oh, okay, also a problem then.

**Comment by zmwangx** [comment]
Although, this could be worked around by downstream projects by specifying a feature set, so unlike the FFmpeg 4.x woes here, the -sys problem isn't a showstopper.

**Pull request closed without merging**
