### PR TITLE
Allow passing muxer options to avformat_write_header

### PR DESCRIPTION
**Pull request by main--**
Perhaps not the best way to do this, but at least it works.

### CODE REVIEW

**Comment by meh** [comment]
It's fine enough now that I implemented `Default` for `Dictionary`.

**Comment by retrry** [comment]
What is the difference between write_header and write_header_with now?

**Comment by retrry** [comment]
What is the difference between write_header and write_header_with now?

**Comment by meh** [comment]
@retrry I totally forgot about that, I reverted the change and made `write_header_with` return the `Dictionary`.

**Pull request merged**
