### PR TITLE
Add interrupt_callback support

### PR DESCRIPTION
**Pull request by retrry**
Hi,
this is my work in progress code on interrupt callback support. I'm looking for reviews and suggestions, as I'm kinda new to Rust. Maybe I'm doing everything wrong. Example code of this implementation usage (cargo run http://stream_url):

```
extern crate libc;
extern crate ffmpeg;

use std::env;
use std::sync::{Arc, Mutex};
use std::time::SystemTime;

use ffmpeg::format;
use libc::{c_void, c_int};

extern fn ffmpeg_callback(opaque: *mut c_void) -> c_int {

    let from_pointer = unsafe { &*(opaque as *mut Arc<Mutex<SystemTime>>) };
    let time = from_pointer.lock().unwrap();
    if time.elapsed().unwrap().as_secs() > 1 {
        println!("Too much time elapsed");
        return 1;
    }
    0
}

fn main() {
    //Initialize ffmpeg
    ffmpeg::init().expect("Cannot init ffmpeg");
    ffmpeg::format::network::init();
    let time = Arc::new(Mutex::new(SystemTime::now()));

    let input = env::args().nth(1).expect("Missing input parameters");
    let interrupt = ffmpeg::interrupt::new(ffmpeg_callback, time.clone());
    let mut ictx = format::input_with_interrupt(&input, interrupt).expect("Can't read codec information from input stream");

    for (_, _) in ictx.packets() {
        let mut update = time.lock().unwrap();
        *update = SystemTime::now();
    }
}

### CODE REVIEW

**Comment by meh** [comment]
Can the interrupt callback be defined after opening the codec? I'm kind of concerned about the proliferation of incompatible `with_` functions, if it can be defined later it would be nice, otherwise it might be wise to go with the builder pattern.

About the API, it would be best if the callback wasn't a raw function, but a `T: FnMut` so closures can be used, to achieve that my advice would be to store into opaque a `Box<FnMut>`, and `callback` would be an internal only function that just casts back the raw pointer to a `Box<FnMut>` and calls it.

**Comment by retrry** [comment]
Hello,
thanks for your fast answer. 
I really didn't want to create a new open_with_ function, but I didn't know how to merge them. What I found from ffmpeg documentation is that interrupt_callback should be set before `avformat_open_input` [1]. This is why I did it this way. What do you mean by builder pattern? Could you provide couple examples for me so I could implement it?

Great idea about `T: FnMut`. I will redo my code like that this week.

[1] https://ffmpeg.org/doxygen/3.2/structAVFormatContext.html#a5b37acfe4024d92ee510064e80920b40

**Comment by meh** [comment]
Something that would be used like the following:

```rust
format::input().options(<Dictionary>).interrupt(|| ...).open()
```

That's the builder pattern, you'd have something like a `struct FormatInputBuilder` with `options` and `interrupt` methods that take `&mut self` and return `&mut Self`, then `open` actually opens the format. (just used the first names that came to my mind for methods and struct).

**Comment by retrry** [comment]
So I've tried to implement callback with FnMut to support closures. Could you check that I understood you correctly? If this is correct I will try to implement builder pattern for open_with_

Implementation usage example:
```
extern crate ffmpeg;

use std::env;
use std::sync::{Arc, Mutex};
use std::time::SystemTime;

use ffmpeg::format;

fn main() {
    //Initialize ffmpeg
    ffmpeg::init().expect("Cannot init ffmpeg");
    ffmpeg::format::network::init();
    let time = Arc::new(Mutex::new(SystemTime::now()));

    let input = env::args().nth(1).expect("Missing input parameters");
    let ffmpeg_callback = || {
        let time = time.lock().unwrap();
        if time.elapsed().unwrap().as_secs() > 1 {
            println!("Too much time elapsed");
            return 1;
        }
        0
    };
    let interrupt = ffmpeg::interrupt::new(Box::new(ffmpeg_callback));
    let mut ictx = format::input_with_interrupt(&input, interrupt)
        .expect("Can't read codec information from input stream");

    for (_, _) in ictx.packets() {
        let mut update = time.lock().unwrap();
        *update = SystemTime::now();
    }
}

**Comment by meh** [comment]
Almost! You just have to hide all that boilerplate away, `format::input_with_interrupt` should be taking the closure directly instead of the `Interrupt`.

Something like this:

```rust
    let input = env::args().nth(1).expect("Missing input parameters");
    let mut ictx = format::input_with_interrupt(&input, || {
        let time = time.lock().unwrap();
        if time.elapsed().unwrap().as_secs() > 1 {
            println!("Too much time elapsed");
            return 1;
        }
        0
    }).expect("Can't read codec information from input stream");
```

Once that's done let's both inspect those unsafe parts carefully to verify it's sound (it looks sound to me).

**Comment by meh** [comment]
Another thing, I asked about it in #rust and it would be better if `callback` wrapped the call to the closure in a `catch_panic`, that's because panicking through FFI boundaries is undefined behavior, so if for some reason the closure panics bad things would happen.

**Comment by retrry** [comment]
Hello,
sorry for slow response times - I was pulled over to different project. So I've removed boilerplate and now pass closure directly to input_with_interrupt. 
I have two questions left:
-- Do you want to do input_with function rewrite to builder pattern with this pull request or lets do it latter?
-- I don't fully understand how to implement EAGAIN[1] error as ffmpeg should return it when callback is called. Could you give directions for me here?

[1] https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/error.c#L66

**Comment by retrry** [comment]
Okay.
So I catch_panic the closure and lets say closure panicked. Should I panic from callback function or silently fail and always return 0 to ffmpeg?

**Comment by meh** [comment]
The `callback` seems to be returning an error code, so what you should do in case of panic is to return the proper error code to tell ffmpeg the callback failed.

Also now that I think of it the closure should probably be returning a `Result<(), Error>` instead of `c_int`, and `callback` should return the proper error code converted from the `Result`.

**Comment by meh** [comment]
>Do you want to do input_with function rewrite to builder pattern with this pull request or lets do it latter?

I think I'll do that myself so I can give some more thought to the API for it, so don't worry about it.

>I don't fully understand how to implement EAGAIN[1] error as ffmpeg should return it when callback is called. Could you give directions for me here?

I think what needs to be done here is to extend `error.rs` to have those error codes as well, so the closure can just return `Result<(), Error>` and then `callback` can just use the `Into<c_int>` implementation to return the proper ffmpeg error code.

**Comment by retrry** [comment]
I don't think that callback is returning error code, so propagating errors from closure doesn't matter.

ff_check_interrupt implementation: https://ffmpeg.org/doxygen/3.2/avio_8c_source.html#l00655
Callign ff_check_interrupt: https://github.com/FFmpeg/FFmpeg/search?utf8=✓&q=ff_check_interrupt

From these I gather that that only, when callback returns 1 it matters. Everything else is ignored. So it seems to me that error propagation from closure doesn't matter and we could leave its return type c_int.
Callback function would look like this:
```
extern "C" fn callback<F>(opaque: *mut c_void) -> c_int
    where F: FnMut() -> c_int
{
    match panic::catch_unwind(|| (unsafe { &mut *(opaque as *mut F) })()) {
        Ok(ret) => ret,
        Err(_) => 0,
    }
}
```
Or if you still want closure returning Result I could do callback function like this:
```
extern "C" fn callback<F>(opaque: *mut c_void) -> c_int
    where F: FnMut() -> Result<(c_int), Error>
{
    match panic::catch_unwind(|| (unsafe { &mut *(opaque as *mut F) })()) {
        Ok(ret) => {
            match ret {
                Ok(r) => r,
                Err(e) => e.into(),
            }
        }
        Err(_) => 0,
    }
}
```
I've added c_int to result, as it should be possible for closure to return 0 to not abort blocking operation.
What do you think?

**Comment by meh** [comment]
Returning a `c_int` would leak out, the user of ffmpeg would have to `extern crate libc` to use it, so regardless of whether the error is meaningful or not, the underlying implementation detail of returning a code should be hidden away.

**Comment by retrry** [comment]
So If I understand you correctly closure would return either Err() or Ok(). 
If closure returned Ok we would assume that this means that we should interrupt and callback returns 1.
If closure returned Err we would assume that we don't need interrupt and callback returns 0.
This way seems counter-intuitive. There was no error in closure, we just didn't want interrupt yet, but we had to return Err.

Or should I just change c_int to i32 so it wouldn't leak out.

Or am I still missing and not understanding something? :)

**Comment by meh** [comment]
Oh, in that case just return a `bool`.

**Comment by retrry** [comment]
I've rebased this branch on https://github.com/meh/rust-ffmpeg/pull/81 as AVIOInterruptCB struct does differ a bit in generated bindings and manual ones (callback is wrapped with Option in generated bindings). I've changed return type for closure to bool. I will test this extensively next week as I will be implementing couple features, which depend on interrupts.

My main question would be this line: https://github.com/meh/rust-ffmpeg/pull/79/commits/12362e12ea4d659d7ecf41a5a4d15f19185cf60d#diff-e1f867dc616b644f7096cb2704c291daR15

When I catch panic from closure, should I silently ignore, or panic here. If I panic here would it still count as going though FFI boundaries as result is consumed by ffmpeg?

**Comment by meh** [comment]
It might make sense to abort, panicking again would still result in undefined behavior, but I don't see any way to tell ffmpeg the callback failed, or am I just not seeing it?

**Comment by retrry** [comment]
I don't think there is a way. Everything apart of 1 is ignored in ff_check_interrupt. So ffmpeg side doesn't care, but silently ignoring closure failure doesn't seem right to me as it wouldn't be what I would expect when using rust-ffmpeg bindings.

**Comment by meh** [comment]
Agree, just call `std::process::abort` in case `catch_unwind` catches a panic, avoids undefined behavior, and you get a proper error.

**Comment by retrry** [comment]
I've made program abort, if closure panics. Do you have any more concerns? And this PR still depends on: https://github.com/meh/rust-ffmpeg/pull/81

**Comment by retrry** [comment]
Rebased this on https://github.com/meh/rust-ffmpeg/pull/81, squashed commits.

**Comment by meh** [comment]
Merged, sorry for the long wait, thanks!

**Pull request closed without merging**
