### PR TITLE
Support actual path in input/open functions

### PR DESCRIPTION
**Pull request by kornelski**
* `impl AsRef` doesn't allow turbofish.
* `AsRef<str>` doesn't allow `&Path`.

### CODE REVIEW

**Comment by meh** [comment]
It was Path before, the reason I moved it to `str` is that can also be a URL.

**Comment by kornelski** [comment]
OK, I've changed it to `OsStr` which is compatible with both `Path` and `str`.

**Comment by meh** [comment]
That works!

**Comment by meh** [comment]
Thanks! :panda_face:

**Pull request merged**
